### ISSUE TITLE
Add Jupyter Example

### ISSUE THREAD

**Issue by jcrubino** [caddyserver/examples#104]
Jupyter (formerly Ipython) is a popular code notebook platform popular in datascience and academia.
The project can serve as a code notebook for python, scala, julia and more.

Here is a working example for python.  
```
example.com {
   proxy / localhost:8888 {
       header_upstream X-Real-IP  {remote}
       header_upstream Host {host}
       header_upstream X-Forwarded-Proto {scheme}
       websocket
  }
}
  
```

**Comment by angristan** [comment]
Hey! If it's working for you, would you mind doing a PR?

**Comment by jcrubino** [comment]
I think it is working.
After I test it again, I will for sure.  
Tomorrow or so.
