### ISSUE TITLE
Please Add Web2py Example

### ISSUE THREAD

**Issue by sugizo** [caddyserver/examples#120]
**Caddfyfile**
```
domain.tld {
    proxy / localhost:8000 {
        transparent
    }
}
```

**README.md**
This is an example configuration for web2py using caddy as proxy the requests to the app server.
Assuming you run web server on the same server with port 8000 either using default web2py rocket server in web2py.py or using anyserver.py (cherrypy, diesel, eventlet, gevent, gunicorn, paste, rocket, tornado, twisted, waitress, wsgiref), otherwise change the server name or ip or server port

**Note**
tested running well with Caddy 0.11.0 (non-commercial use only) and web2py version 2.16.1-stable

**Comment by mholt** [comment]
Feel free to submit a pull request. :) Thanks!

**Comment by sugizo** [comment]
**In Terminal**
```
git clone https://github.com/sugizo/examples.git
cd examples
git remote -v
git remote add upstream https://github.com/caddyserver/examples.git
git remote -v
git fetch upstream
git checkout master
git merge upstream/master
git checkout -b add_web2py
git checkout add_web2py
mkdir web2py
cat << EOF > web2py/Caddyfile
domain.tld {
    proxy / localhost:8000 {
        transparent
    }
}
EOF
cat << EOF > web2py/README.md
# Web2py

This is an example configuration for web2py using caddy as proxy the requests to the app server.
Assuming you run web server on the same server with port 8000 either using default web2py rocket server in web2py.py or using anyserver.py (cherrypy, diesel, eventlet, gevent, gunicorn, paste, rocket, tornado, twisted, waitress, wsgiref), otherwise change the server name or ip or server port
EOF
git add --all
git commit -am "add web2py"
git push origin add_web2py
open https://github.com/caddyserver/examples/compare/master...sugizo:add_web2py
```

**In Browser**
Click Create pull request and Fill the Subject and Message, then submit
