### ISSUE TITLE
[Help] Switch service from HTTP to HTTPS

### ISSUE THREAD

**Issue by giopas** [caddyserver/examples#125]
Hi,

I would like to move one of my proxied services from HTTP to HTTPS.

Caddy runs with the following command:

`caddy -agree -port 20015 -root /home/Qhttpd -log $QPKG_ROOT/var/logs/caddy.log -pidfile /var/run/caddy.pid -conf caddy.conf`

and in the caddy.conf file I have the following block:

```
http://service.mydomain.com:8963 {
	import gzipconf
	import addheader
	proxy / http://192.168.2.87:8989 {
		keepalive 32
		transparent
		websocket
	}
}
```

Indeed on my router I have forwarded the port 80 to port 8989 of the IP where Caddy is running.

So far so good.

What I would like is to change "service" in HTTPS (in this example, using port 9898 in the service config).

I have therefore tried to change the config file as follows:

```
https://service.mydomain.com:8963 {
	import gzipconf
	import addheader
	proxy / https://192.168.2.87:9898 {
		keepalive 32
		transparent
		websocket
	}
}
```

and I forwarded port 443 of the router to the same port 8989 if the IP where Caddy is running.

But this does not work. What am I missing here?

Thanks in advance for your help!

**Comment by mholt** [comment]
Hey @giopas -- please try asking in our forum instead: https://caddy.community

This issue tracker is for the examples repository only. Thanks!
