### ISSUE TITLE
unrecognized directive: on

### ISSUE THREAD

**Issue by xja** [caddyserver/examples#173]
Caddyfile is almost exact the same as the example here, except the change of root path, however when i tried to execute `caddy.exe run`, the following error occurred:

using adjacent Caddyfile
run: adapting config using caddyfile: Caddyfile:3: unrecognized directive: on

output of `caddy.exe version`:
v2.0.0-beta.14 h1:QX1hRMfTA5sel53o5SuON1ys50at6yuSAnPr56sLeK8=

**Comment by xja** [comment]
here is the Caddyfile:

:8888 {
	root D:\WWW
	on startup php_cgi2.bat &
	fastcgi / 127.0.0.1:6545 php
}

**Comment by tobya** [comment]
On hasnt been implemetned in V2.

You can use V1 and it will work perfectly.

https://caddyserver.com/v1/download

**Comment by xja** [comment]
> On hasnt been implemetned in V2.
> 
> You can use V1 and it will work perfectly.
> 
> https://caddyserver.com/v1/download

Ok, thank you so much!
