### ISSUE TITLE
Reverse proxy example does not work

### ISSUE THREAD

**Issue by pydo** [caddyserver/examples#174]
Caddy version: `v2.0.0-beta.14 h1:QX1hRMfTA5sel53o5SuON1ys50at6yuSAnPr56sLeK8=`

**Repro steps**

1.Create this `Caddyfile`  https://github.com/caddyserver/examples/blob/master/headphones/Caddyfile
2. Run `caddy run` in the same directory as the `Caddyfile`

**Expected behavior**

Caddy runs the reverse proxy

**Actual behavior**

`proxy` directive is not recognized
```
caddy run
2020/02/23 17:17:50.604	INFO	using adjacent Caddyfile
run: adapting config using caddyfile: Caddyfile:2: unrecognized directive: proxy
```

**Comment by pydo** [comment]
Switching the proxy directive to reverse_proxy doesn't fix the issue:

```
cat Caddyfile 
myheadphones.com {
    reverse_proxy / localhost:8181 {
        transparent
    }
}

```

```
 caddy run
2020/02/23 17:28:02.941	INFO	using adjacent Caddyfile
run: adapting config using caddyfile: parsing caddyfile tokens for 'reverse_proxy': Caddyfile:3 - Error during parsing: unrecognized subdirective transparent
```

**Comment by mholt** [comment]
These examples are for v1, but you're using v2.

We'll change this repository to v2 at some point this year I think.

V2 proxying docs are here: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy
