### ISSUE TITLE
markdown example doesn't work

### ISSUE THREAD

**Issue by kstenerud** [caddyserver/examples#177]
Using caddy built from master:

```
../caddy/cmd/caddy/caddy run
2020/03/25 15:50:31.948	INFO	using adjacent Caddyfile
run: adapting config using caddyfile: Caddyfile:3: unrecognized directive: markdown
```

**Comment by mholt** [comment]
These examples are for v1, I need to update the repo to make that clearer. :P

In v2, there is no markdown directive; but [templates](https://caddyserver.com/docs/caddyfile/directives/templates) can render markdown!
