### ISSUE TITLE
HPKP for LE or enhanced security headers

### ISSUE THREAD

**Issue by ghost** [caddyserver/examples#41]
Hi!
if anyone is interested in HPKP for LE

```
header / {
    Public-Key-Pins "pin-sha256=\"Vjs8r4z+80wjNcr1YKepWQboSIRi63WsWXhIMN+eWys=\"; pin-sha256=\"sRHdihwgkaib1P1gxX8HFszlD+7/gTfNvuAybgLPNis=\"; pin-sha256=\"YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg=\"; pin-sha256=\"C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M=\"; max-age=7776000;"
}
```

`Vjs8r4z+80wjNcr1YKepWQboSIRi63WsWXhIMN+eWys=` is DST Root CA X3 (root for cross sign)
`YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg=` is Let's Encrypt Authority X3 (active) [check](https://ssl-tools.net/subjects/7ee66ae7729ab3fcf8a220646c16a12d6071085d)
`sRHdihwgkaib1P1gxX8HFszlD+7/gTfNvuAybgLPNis=` is Let's Encrypt Authority X4 (backup)
`C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M=` is ISRG Root X1 (new LE root) [check](https://ssl-tools.net/subjects/281aea4e6a11200e3949b766237385489c2e8792)

[LE Cross Signing](https://letsencrypt.org/certs/isrg-keys.png)

Please double check again and please have a look at ECDSA key's which will come this year.

Suggestions welcome

**Comment by mholt** [comment]
Thanks for commenting with this, @ghost. For any others who find this: HPKP is a sharp blade, I recommend extreme care when using it.
