### ISSUE TITLE
The Seafile examples don't work

### ISSUE THREAD

**Issue by OmgImAlexis** [caddyserver/examples#44]
The current examples for Seafile don't work at all and just end up in a 404.

For example accessing `http://192.168.1.150:8082/files/66aed549-4c3c-4f3d-a15d-c19be8ac0193/test.mkv` works fine yet `https://example_host.com/seafhttp/files/66aed549-4c3c-4f3d-a15d-c19be8ac0193/test.mkv` doesn't even though I'm using I'm using the same setup as the example.

```
root@Tower:/mnt/user/appdata/caddy# cat Caddyfile 
seafile.home.wvvw.me {
    tls xo@wvvw.me
    proxy / 192.168.1.150:8000 {
        transparent
    }
    gzip
    log stdout
    errors stdout
}

seafile.home.wvvw.me/seafhttp {
    tls xo@wvvw.me
    proxy / 192.168.1.150:8082 {
       transparent
    }
    rewrite /seafhttp {
        regexp (.*)
        to     {1}
    }
    gzip
    log stdout
    errors stdout
}
```

https://github.com/haiwen/seafile/issues/1698
https://forum.caddyserver.com/t/running-seafile-and-seahub-behind-caddy-proxy/233

Ref: https://github.com/caddyserver/examples/pull/30

**Comment by jnaskali** [comment]
Having the same problem. I used 'without' instead of regexp, but the problem remains.
```
seafile.server/seafhttp {
  proxy / 127.0.0.1:8082 {
    transparent
    without /seafhttp
  }
}
```
The examples also lack the /media rewrite used in nxing/apache config files, though it doesn't seem to matter much:
```
seafile.server/media {
  root /home/user/haiwen/seafile-server-latest/seahub/media
}
```

**Comment by OmgImAlexis** [comment]
I completely forgot I had this issue open but for some reason this exact config is what I'm using now and I don't have any issues with it.

**Comment by jnaskali** [comment]
Baffling... Did you change anything else with your setup?

**Comment by OmgImAlexis** [comment]
I think the only thing I change was in the admin settings area where I changed these two so they match with my Caddyfile. From memory before this I had it set to `192.168.1.150` which is the internal IP for the seafile server.

SERVICE_URL = https://seafile.home.wvvw.me
FILE_SERVER_ROOT = https://seafile.home.wvvw.me/seafhttp

**Comment by jnaskali** [comment]
Thanks. I did that already before switching over from nginx, which worked perfectly.

Weird...

**Comment by jnaskali** [comment]
Just in case someone else runs into the same problem...
There is a bug with 'without' in 0.10: https://github.com/mholt/caddy/issues/1604

I rolled back to 0.9.5 and my config started working:

```
seafile.server {
  proxy / 127.0.0.1:8000 {
    transparent
  }
  gzip
}
seafile.server/seafhttp {
  proxy / 127.0.0.1:8082 {
    without /seafhttp
    transparent
  }
  gzip
}
seafile.server/media {
  root /home/seafile/seafile-server-latest/seahub/media
  gzip
}
```
