### ISSUE TITLE
dokuwiki: media not loaded

### ISSUE THREAD

**Issue by davidak** [caddyserver/examples#45]
hello @fanningert,

thanks for sharing this config!

Images from URLs like `https://example.com/_media/mods/ac_sniper_2_0.jpg` are not loaded correctly.

it works when replace the `/_media` rewrite with:

```
    rewrite /_media {
        r (.*)
        to /lib/exe/fetch.php?media={1}
    }
```
Source: https://minimum.io/configuring-dokuwiki-and-pretty-urls-with-caddy/

Im using dokuwiki Release 2016-06-26a "Elenor of Tsort", maybe this example is correct for newer versions. Then ignore this issue.

**Comment by mholt** [comment]
Did you ever upgrade and retry? If it's still a problem, feel free to submit a PR.

**Comment by priyadarshan** [comment]
I am having same issue with latest DokuWiki, Release 2018-04-22a “Greebo”.

The solution suggested by @davidak works for me.
