### ISSUE TITLE
Common WP MultiSite

### ISSUE THREAD

**Issue by triplekdev** [caddyserver/examples#5]
Hi,

Any example on common Wordpress w/ Caddyfile that handles multisite w/ named hosts?
`http://estore.dev` w/ a subsite & child theme that is `http://caddy.estore.dev`

Thanks!

**Comment by mholt** [comment]
You can set up multiple sites in your Caddyfile like this:

```
estore.dev {
    ...
}

caddy.estore.dev {
    ...
}
```

Not really sure what you mean otherwise, but there is a wordpress example in this repo already. Hopefully this is helfpul.

**Comment by triplekdev** [comment]
Hi Matt,

Sorry, what i mean really is, in-the future will caddy provide a auto modification for `/etc/hosts` for this named virtual hosts? from the topic Wordpress multisite, websites are created dynamically from Network, is it possible for `import "caddy/exec/estores_domains.sh"` execute it? and parse the return from the sh file; which append like `caddy.estore.dev { ... } some_caddy.estore.dev { ... }`? or does `import` maybe allow to execute scripts? so maybe the `Caddyfile` will look like:

````

estore.dev {
  ...
  ...
}

# estores_domains.sh -- will just execute php job to get "stores" from database 
# and printout a formatted string like estore.dev above.
import exec:caddy/exec/estores_domains.sh

````

I read on discussion at `Caddyserver` github page that you are making it to support `*.estore.dev`, it would be nice that caddy will also handles the `/etc/hosts` if possible for quick and easy local dev.

but `import exec:...` for example would be just very nice to have as-well.



Best Regards!

**Comment by mholt** [comment]
There are no plans for Caddy to modify the hosts file on the system, or run commands when the Caddyfile is being parsed. (The startup/shutdown directives do this when the server is starting.) It's possible that host file rewriting could be an add-on, but not something that's currently fit for showing off in this examples repository. Thanks for the feedback!

**Comment by triplekdev** [comment]
Thanks for the answer. Looking forward w/ Caddyserver.
