### ISSUE TITLE
Collabora proxy example ?

### ISSUE THREAD

**Issue by Technowix** [caddyserver/examples#50]
Hello,
I'm having hard time to get collabora working in my setup, and don't find how to proxy it well.
https://www.collaboraoffice.com/code/
If someone with a better understanding of nginx/apache proxy + caddyfile can find something, that would be awesome ^^'

**Comment by tobya** [comment]
Hello there may be a few more people able to help at the caddy forum.  HTTPS://forum.caddyserver.com
