### ISSUE TITLE
Which permissions you should give your wordpress folder? 

### ISSUE THREAD

**Issue by Schokolader** [caddyserver/examples#57]
Which permissions you should give your wordpress folder that Caddy works well and secure with wordpress? 
Like this: 

cd /var/www/mein-wordpress
chown www-data:www-data -R *          
find . -type d -exec chmod 755 {} \;  
find . -type f -exec chmod 644 {} \;  

but when I use this above I can't install some new themes. Do you know what to do?

**Comment by mholt** [comment]
Hi @Schokolader  - thanks for your question! I don't know the answer off-hand, but I'm sure somebody at the [forum](https://caddy.community) would be able to help out.
