### ISSUE TITLE
could you please add a gocd server example?

### ISSUE THREAD

**Issue by rahulmr** [caddyserver/examples#67]
I wanted run gocd server and use Let's Encrypt certificate for the same. The server http runs on 8153 and https runs on 8154 by default.

Is it possible to put an example?

**Comment by Timi7007** [comment]
A possible solution would be to run the gocd server in http-only mode on localhost and use a reverse proxy to serve on port 443, while redirecting port 80 to 443.

~~~
gocd.example.com {
	proxy / localhost:8153
}
~~~

Another way (using the default gocd config) could be:
~~~
http://gocd.example.com {
	proxy / localhost:8153
}

https://gocd.example.com {
	proxy / localhost:8154
}
~~~
This would result in the gocd HTTP server being available on ports 8153 and 80, while the gocd HTTPS server would be at 8154 and 443. HTTP requests would however not be redirected to HTTPS and accessing port 8154 directly could serve a "certificate not trusted"-error as the Let's Encrypt cert would only be on port 443.
