### ISSUE TITLE
the wordpress redirect causes jetpack to fail (fix proposed)

### ISSUE THREAD

**Issue by jbmanos** [caddyserver/examples#71]
the wordpress example has:
`to {path} {path}/ /index.php?_url={uri}`

this redirect pattern will cause jetpack features (such as related posts) to fail because jetpack uses a flat query and not the url= pattern.  It should be fixed to this:

`to {path} {path}/ /index.php?{query}`

the corrected redirect pattern allows jetpack to run features (related posts, for one) and tends to allow nonstandard API requests work again.   I didn't want to fork the entire examples project just to propose this one change

**Comment by mholt** [comment]
Thanks for the note, John! I haven't verified this but I'll take your word for it that this still works for WordPress users without jetpack.

**Comment by jbmanos** [comment]
It does.   All the other rewrites work fine with this.
