### ISSUE TITLE
How  to make  a rewrite rule of "Redirect Trailing Slashes If Not A Folder."

### ISSUE THREAD

**Issue by fanybook** [caddyserver/examples#88]
Like  this :

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

**Comment by fanybook** [comment]
caddy's rewrite can't use 301
caddy's redir can't use regexp 

:(

**Comment by fanybook** [comment]
caddy's rewrite & redir can't -d  -f

**Comment by tobya** [comment]
@Fanybook thank you for the issue.   You might find more help in solving your issue if you post it to the community forum at https://caddy.community
