### ISSUE TITLE
help-wanted - security testing 

### ISSUE THREAD

**Issue by ooogwayduh-rock** [caddyserver/examples#9]
- use <b>Kali Linux: Armitage, Owasp-Zap</B> to test for security and performance
- operate Kali Linux via scripting on Azure or AWS
- setup <b>target one as caddyserver</b> on port 80, 443 which internally redirects to port 8080
- setup <b>target two as nginx</b> on port 80, 443 which internally redirects to port 8080
- at port 8080 serve <b>gopl.io/ch1/server1</b>
- on a daily or weekly basis trigger and fire Kali Linux at the two targets
- use <b>Geckoboard</b> to graph and compare performance and security of target one vs two
- aim is to track nginx and boost caddyserver to that level of performance and security

**Comment by MSF-Jarvis** [comment]
I do not see how it is related to caddyserver,com/examples @ooogwayduh-rock

**Comment by ooogwayduh-rock** [comment]
Prompted by mholt.

**Comment by ooogwayduh-rock** [comment]
Include default settings in example to PASS tests by the following:-

docker run -t owasp/zap2docker-stable zap-baseline.py -t http://example.new 

Specifically for example:- 

WARN: Incomplete or No Cache-control and Pragmatic HTTP Header Set

**Comment by mholt** [comment]
Well, it was your idea ;) I said I was open to the PR, not really sure where it was going. I don't use Docker nor do I advocate its use with Go programs, so I dunno. Maybe these ideas would be better served as blog posts on your blog.

**Comment by ooogwayduh-rock** [comment]
Was aiming for Caddyserver to be http2, safe, secure out of the box because the above Docker test is applied as part of the release process.

**Comment by mholt** [comment]
Oh; I didn't know it was suggested to be part of the release process.

**Comment by ooogwayduh-rock** [comment]
I dunno. Either. 😬
