### ISSUE TITLE
Add Node.js Example

### ISSUE THREAD

**Issue by Mr-Que** [caddyserver/examples#96]
Please add a Node.js example

**Comment by Timi7007** [comment]
What exactly do you mean by "Node.js example"? Are you running an npm "app" and want to reverse-proxy it through Caddy? 

E.g.: If you were trying to run a small Node.js application, like [an Agar.io clone](https://github.com/huytd/agar.io-clone), you would have a local webserver running on 127.0.0.1:3000 by npm and could use the [HTTPSproxy](https://github.com/caddyserver/examples/tree/master/httpsproxy) example to make it available over port 80 & 443. 
Port 80 (HTTP) would automatically redirect to port 443 which would than serve your app over HTTPS.
Real-world example: 
~~~
cells.timlukas.de {
	proxy / localhost:3000
}
~~~
This configuration does exactly as described: https://cells.timlukas.de
