### ISSUE TITLE
how to remove caddy

### ISSUE THREAD

**Issue by Adagior** [caddyserver/examples#97]
how to remove caddy completely

**Comment by mholt** [comment]
Just delete the executable file.

**Comment by Adagior** [comment]
other plugin have get data from caddy  have 403 410 error

**Comment by Adagior** [comment]
@mholt
i mean completely   
 the /root/.caddy/have some  
        /etc/caddy/ssl  

is there a uninstall.sh  here

**Comment by tobya** [comment]
There is no uninstall.sh but perhaps someone could try to put a wiki page of where files are written to.

**Comment by mholt** [comment]
Caddy doesn't write to any files except $HOME/.caddy ($CADDYPATH). If there is an /etc/caddy/ssl folder, it was put there by something else (like a sysadmin or a script), so that's up to you to clean up.
